# Generated by Django 6.0.7 on 2026-09-20 06:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('assigned_to__isnull', False), models.Q(('status', 'done'), _negated=True)), fields=['due_date'], name='task_due_active_idx'),
        ),
    ]
