# Generated by Django 6.0.7 on 2026-09-20 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'task_due_soon')), fields=('user', 'task', 'type'), name='unique_due_soon_user_task'),
        ),
    ]
